### ISSUE TITLE
paddle 版本兼容问题

### ISSUE THREAD

**Issue by ReverseSacle** [jm12138/deep_sort_paddle#4]
想问问，怎样把低版本的paddle_detection eport导出的文件用于这个deepsort版本。旧版的paddle模型文件无法适用于这个新版本的deepsort。

**Comment by Irvingao** [comment]
你git clone deepsort以前版本的代码就行

**Comment by ReverseSacle** [comment]
> 你git clone deepsort以前版本的代码就行

谢谢回复。
关于使用旧的版本deepsort会有一个问题。
用的是旧版paddle_detection的YOLOv4模型导出的文件。
<img width="871" alt="问题" src="https://user-images.githubusercontent.com/73418195/121359250-deb1b480-c965-11eb-83ec-26d57e4fe093.png">
